name: xokomola
#markdown: redcarpet
markdown: kramdown
#markdown: KramdownPygments
highlighter: pygments
# comments defaults: posts (on), pages (off)
comments: 0
# show sidebar
sidebar: 1
banner: city
